pipeline {

    agent any

    stages {
        stage('Build docker image') {
            steps {
                sh "sudo docker build . -t postgres_to_csv-${GIT_BRANCH}:1.0.0-${BUILD_NUMBER}"
            }
        }
        stage('Delete previous version docker container') {
            steps {
                sh "sudo docker rm -f postgres_to_csv-live"
            }
        }
        stage('Create and activate docker container for live version') {
            steps {
                sh "sudo docker run --name postgres_to_csv-live -d postgres_to_csv-${GIT_BRANCH}:1.0.0-${BUILD_NUMBER}"
            }
        }
    }
    post {
        success {
            echo "All done."
            echo "Live version has been deployed."
        }
    }
}
